# Generated by Django 4.2.20 on 2025-06-02 11:01

import core.utils.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customs_general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedDocumentsBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('record_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('system_note', models.TextField(blank=True, null=True)),
                ('doc_name', models.CharField(max_length=255)),
                ('doc_file', models.FileField(upload_to=core.utils.utils.date_based_upload_path)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('data_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customs_general.datasource')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Yüklenen Dökümanlar',
                'verbose_name_plural': 'Yüklenen Dökümanlar',
            },
        ),
    ]
