# Generated by Django 4.2.20 on 2025-03-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalInfoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Tamamlayıcı Bilgi Kodları',
                'verbose_name_plural': 'Tamamlayıcı Bilgi Kodları',
            },
        ),
        migrations.CreateModel(
            name='AirlineCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Uçak Şirketi Kodları',
                'verbose_name_plural': 'Uçak Şirketi Kodları',
            },
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Havalimanı Kodları',
                'verbose_name_plural': 'Havalimanı Kodları',
            },
        ),
        migrations.CreateModel(
            name='AntiDumpingCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Anti-Damping Vergisi Üreticisi Gönderici Firma Kodları',
                'verbose_name_plural': 'Anti-Damping Vergisi Üreticisi Gönderici Firma Kodları',
            },
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('swift_code', models.CharField(max_length=30, unique=True)),
                ('bank_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=40)),
                ('fax_number', models.CharField(max_length=100)),
                ('web_address', models.CharField(max_length=255)),
                ('kep_address', models.CharField(max_length=100)),
                ('eft_number', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Banka Kodları',
                'verbose_name_plural': 'Banka Kodları',
            },
        ),
        migrations.CreateModel(
            name='ContainerCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Kap Kodları',
                'verbose_name_plural': 'Kap Kodları',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Ülke Kodları',
                'verbose_name_plural': 'Ülke Kodları',
            },
        ),
        migrations.CreateModel(
            name='CurrencyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Döviz Cinsi Kodları',
                'verbose_name_plural': 'Döviz Cinsi Kodları',
            },
        ),
        migrations.CreateModel(
            name='CustomsOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customs_code', models.CharField(max_length=50)),
                ('customs_name', models.CharField(max_length=255)),
                ('treasury_code', models.CharField(max_length=50)),
                ('treasury_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Gümrük İdareleri ve Saymanlık Kodları',
                'verbose_name_plural': 'Gümrük İdareleri ve Saymanlık Kodları',
            },
        ),
        migrations.CreateModel(
            name='DeliveryMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Teslim Şekli Kodları',
                'verbose_name_plural': 'Teslim Şekli Kodları',
            },
        ),
        migrations.CreateModel(
            name='Depot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depot_code', models.CharField(max_length=10, unique=True)),
                ('depot_name', models.CharField(max_length=255)),
                ('customs_name', models.CharField(max_length=255)),
                ('customs_code', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Antrepo Kodları',
                'verbose_name_plural': 'Antrepo Kodları',
            },
        ),
        migrations.CreateModel(
            name='ExemptionCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Muafiyet Kodları',
                'verbose_name_plural': 'Muafiyet Kodları',
            },
        ),
        migrations.CreateModel(
            name='Harbor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Liman Kodları',
                'verbose_name_plural': 'Liman Kodları',
            },
        ),
        migrations.CreateModel(
            name='InternationalAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Uluslararası Anlaşma Kodları',
                'verbose_name_plural': 'Uluslararası Anlaşma Kodları',
            },
        ),
        migrations.CreateModel(
            name='MeasurementUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Ölçü Birimleri Kodları',
                'verbose_name_plural': 'Ölçü Birimleri Kodları',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Ödeme Şekilleri',
                'verbose_name_plural': 'Ödeme Şekilleri',
            },
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Uluslararası Liman Kodları',
                'verbose_name_plural': 'Uluslararası Liman Kodları',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'STM bağlı il kodları',
                'verbose_name_plural': 'STM bağlı il kodları',
            },
        ),
        migrations.CreateModel(
            name='RegimeCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Rejim Kodları',
                'verbose_name_plural': 'Rejim Kodları',
            },
        ),
        migrations.CreateModel(
            name='RequiredDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'İstenen Döküman Kodları',
                'verbose_name_plural': 'İstenen Döküman Kodları',
            },
        ),
        migrations.CreateModel(
            name='SimplifiedProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Basitleştirilmiş Usul Kodları',
                'verbose_name_plural': 'Basitleştirilmiş Usul Kodları',
            },
        ),
        migrations.CreateModel(
            name='TaxCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Güncel Vergi Kodları',
                'verbose_name_plural': 'Güncel Vergi Kodları',
            },
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'İşlem Niteliği Kodları',
                'verbose_name_plural': 'İşlem Niteliği Kodları',
            },
        ),
        migrations.CreateModel(
            name='TransportType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Taşıma Türleri Kodları',
                'verbose_name_plural': 'Taşıma Türleri Kodları',
            },
        ),
        migrations.CreateModel(
            name='TransportVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Taşıma Araçları',
                'verbose_name_plural': 'Taşıma Araçları',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse_code', models.CharField(max_length=10)),
                ('warehouse_name', models.CharField(max_length=255)),
                ('customs_name', models.CharField(max_length=255)),
                ('customs_code', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Ambar Kodları',
                'verbose_name_plural': 'Ambar Kodları',
            },
        ),
    ]
