# Generated by Django 4.2.20 on 2025-04-15 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalInfoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Tamamlayıcı Bilgi Kodları',
                'verbose_name_plural': 'Tamamlayıcı Bilgi Kodları',
            },
        ),
        migrations.CreateModel(
            name='AirlineCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Uçak Şirketi Kodları',
                'verbose_name_plural': 'Uçak Şirketi Kodları',
            },
        ),
        migrations.CreateModel(
            name='AntiDumpingCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Anti-Damping Vergisi Üreticisi Gönderici Firma Kodları',
                'verbose_name_plural': 'Anti-Damping Vergisi Üreticisi Gönderici Firma Kodları',
            },
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('swift_code', models.CharField(max_length=50, null=True)),
                ('bank_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255, null=True)),
                ('eft_number', models.IntegerField(null=True)),
                ('bank_logo', models.ImageField(blank=True, null=True, upload_to='customs_general/', verbose_name='Ürün görseli')),
            ],
            options={
                'verbose_name': 'Banka Kodları',
                'verbose_name_plural': 'Banka Kodları',
            },
        ),
        migrations.CreateModel(
            name='ChiefCustomsOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Başgümrük Müdürlükleri',
                'verbose_name_plural': 'Başgümrük Müdürlükleri',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=255)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Şehirler',
                'verbose_name_plural': 'Şehirler',
            },
        ),
        migrations.CreateModel(
            name='ContainerCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Kap Kodları',
                'verbose_name_plural': 'Kap Kodları',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('country_code_alpha2', models.CharField(max_length=100)),
                ('country_code_alpha3', models.CharField(max_length=100)),
                ('country_name_tr', models.CharField(max_length=100)),
                ('country_name_en', models.CharField(max_length=100)),
                ('country_number', models.CharField(max_length=100)),
                ('country_lang_code', models.CharField(max_length=100, null=True)),
                ('country_phone_code', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Ülke Kodları',
                'verbose_name_plural': 'Ülke Kodları',
            },
        ),
        migrations.CreateModel(
            name='CurrencyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('currency_code_3_alpha', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('name_tr', models.CharField(max_length=150)),
                ('minor_unit', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Döviz Cinsi Kodları',
                'verbose_name_plural': 'Döviz Cinsi Kodları',
            },
        ),
        migrations.CreateModel(
            name='CustomerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Müşteri tipleri',
                'verbose_name_plural': 'Müşteri tipleri',
            },
        ),
        migrations.CreateModel(
            name='CustomsOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=255)),
                ('chief_customs_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customs_general.chiefcustomsoffice')),
                ('city_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customs_general.city')),
            ],
            options={
                'verbose_name': 'Gümrük İdareleri ve Saymanlık Kodları',
                'verbose_name_plural': 'Gümrük İdareleri ve Saymanlık Kodları',
            },
        ),
        migrations.CreateModel(
            name='CustomsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Gümrük tipleri',
                'verbose_name_plural': 'Gümrük tipleri',
            },
        ),
        migrations.CreateModel(
            name='DeliveryMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Teslim Şekli Kodları',
                'verbose_name_plural': 'Teslim Şekli Kodları',
            },
        ),
        migrations.CreateModel(
            name='ExemptionCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Muafiyet Kodları',
                'verbose_name_plural': 'Muafiyet Kodları',
            },
        ),
        migrations.CreateModel(
            name='Harbor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Liman Kodları',
                'verbose_name_plural': 'Liman Kodları',
            },
        ),
        migrations.CreateModel(
            name='InternationalAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Uluslararası Anlaşma Kodları',
                'verbose_name_plural': 'Uluslararası Anlaşma Kodları',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('risk_status', models.CharField(max_length=100)),
                ('usage_status', models.CharField(max_length=100)),
                ('edi_code', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Ödeme Şekilleri',
                'verbose_name_plural': 'Ödeme Şekilleri',
            },
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=150)),
                ('risk_status', models.CharField(max_length=100)),
                ('usage_status', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Ödeme Tipleri',
                'verbose_name_plural': 'Ödeme Tipleri',
            },
        ),
        migrations.CreateModel(
            name='QuantityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
                ('edi_code', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Miktar Cinsleri',
                'verbose_name_plural': 'Miktar cinsleri',
            },
        ),
        migrations.CreateModel(
            name='RegimeCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Rejim Kodları',
                'verbose_name_plural': 'Rejim Kodları',
            },
        ),
        migrations.CreateModel(
            name='RequiredDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=70)),
                ('name', models.CharField(max_length=255)),
                ('edi_code', models.CharField(max_length=150)),
                ('name_en', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'İstenen Döküman Kodları',
                'verbose_name_plural': 'İstenen Döküman Kodları',
            },
        ),
        migrations.CreateModel(
            name='SimplifiedProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Basitleştirilmiş Usul Kodları',
                'verbose_name_plural': 'Basitleştirilmiş Usul Kodları',
            },
        ),
        migrations.CreateModel(
            name='TaxCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('tax_ratio', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'Güncel Vergi Kodları',
                'verbose_name_plural': 'Güncel Vergi Kodları',
            },
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'İşlem Niteliği Kodları',
                'verbose_name_plural': 'İşlem Niteliği Kodları',
            },
        ),
        migrations.CreateModel(
            name='TransportType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name_tr', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255, null=True)),
                ('edi_code', models.IntegerField(null=True)),
                ('e_invoice_code', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'Taşıma Türleri Kodları',
                'verbose_name_plural': 'Taşıma Türleri Kodları',
            },
        ),
        migrations.CreateModel(
            name='TransportVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Taşıma Araçları',
                'verbose_name_plural': 'Taşıma Araçları',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('warehouse_code', models.CharField(max_length=10)),
                ('warehouse_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Ambar Kodları',
                'verbose_name_plural': 'Ambar Kodları',
            },
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(blank=True, max_length=60, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('city_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customs_general.city')),
                ('country_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customs_general.country')),
            ],
            options={
                'verbose_name': 'Uluslararası Liman Kodları',
                'verbose_name_plural': 'Uluslararası Liman Kodları',
            },
        ),
        migrations.CreateModel(
            name='GtipCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=255)),
                ('quantity', models.CharField(max_length=50)),
                ('tax_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customs_general.taxcode')),
            ],
            options={
                'verbose_name': 'GTİP Kodları',
                'verbose_name_plural': 'GTİP Kodları',
            },
        ),
        migrations.CreateModel(
            name='Depot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('depot_code', models.CharField(max_length=60)),
                ('depot_name', models.CharField(max_length=255)),
                ('customs_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customs_general.customsoffice')),
                ('warehouse_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customs_general.warehouse')),
            ],
            options={
                'verbose_name': 'Antrepo Kodları',
                'verbose_name_plural': 'Antrepo Kodları',
            },
        ),
        migrations.AddField(
            model_name='customsoffice',
            name='customs_type_id',
            field=models.ManyToManyField(blank=True, null=True, to='customs_general.customstype'),
        ),
        migrations.AddField(
            model_name='country',
            name='currency_id',
            field=models.ManyToManyField(blank=True, null=True, to='customs_general.currencytype'),
        ),
        migrations.AddField(
            model_name='city',
            name='country_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customs_general.country'),
        ),
        migrations.CreateModel(
            name='BankBranches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('branches_code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('bank_id', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='customs_general.bank')),
                ('city_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customs_general.city')),
            ],
            options={
                'verbose_name': 'Banka şubeleri',
                'verbose_name_plural': 'Banka şubeleri',
            },
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('code_iata', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('code_icao', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('latitude_degree', models.CharField(blank=True, max_length=80, null=True)),
                ('longitude_degree', models.CharField(blank=True, max_length=100, null=True)),
                ('city_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customs_general.city')),
                ('country_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customs_general.country')),
            ],
            options={
                'verbose_name': 'Havalimanı Kodları',
                'verbose_name_plural': 'Havalimanı Kodları',
            },
        ),
    ]
