# Generated by Django 4.2.20 on 2025-03-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customs_general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuantityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
                ('code', models.CharField(max_length=255)),
                ('code_2', models.CharField(max_length=255)),
                ('edi_code', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Miktar Cinsleri',
                'verbose_name_plural': 'Miktar cinsleri',
            },
        ),
    ]
