# Generated by Django 4.2.20 on 2025-04-16 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customs_general', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customs_general.datasource'),
        ),
    ]
