# Generated by Django 4.2.20 on 2025-03-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customs_general', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencytype',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
