# Generated by Django 4.2.20 on 2025-04-14 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customs_general', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customertype',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
