# Generated by Django 4.2.20 on 2025-03-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customs_general', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='swift_code',
            field=models.CharField(max_length=50),
        ),
    ]
