# Generated by Django 4.2.20 on 2025-04-16 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customs_general', '0002_city_data_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='port',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customs_general.datasource'),
        ),
    ]
