# Generated by Django 4.2.20 on 2025-03-17 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customs_general', '0002_alter_bank_swift_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankBranches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branches_number', models.CharField(max_length=50)),
                ('branches_name', models.CharField(max_length=255)),
                ('branch_acc_number', models.CharField(max_length=255)),
                ('bank_connection', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='customs_general.bank')),
            ],
            options={
                'verbose_name': 'Banka şubeleri',
                'verbose_name_plural': 'Banka şubeleri',
            },
        ),
    ]
