# Generated by Django 4.2.20 on 2025-03-12 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customs_general', '0002_alter_currencytype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customsoffice',
            name='customs_code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='customsoffice',
            name='treasury_code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
