# Generated by Django 4.2.20 on 2025-04-14 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customs_general', '0002_alter_customertype_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankbranches',
            old_name='branches_number',
            new_name='branches_code',
        ),
        migrations.RemoveField(
            model_name='bankbranches',
            name='branch_acc_number',
        ),
        migrations.AddField(
            model_name='bankbranches',
            name='city_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customs_general.city'),
        ),
    ]
