# Generated by Django 4.2.20 on 2025-03-19 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customs_general', '0002_quantitytype'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
                ('code', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Müşteri tiplerş',
                'verbose_name_plural': 'Müşteri tipleri',
            },
        ),
    ]
