# Generated by Django 4.2.20 on 2025-03-17 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customs_general', '0003_bankbranches'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='edi_code',
            field=models.CharField(default=22, max_length=100),
            preserve_default=False,
        ),
    ]
