# Generated by Django 4.2.20 on 2025-04-16 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customs_general', '0003_port_data_source'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymenttype',
            old_name='risk_status',
            new_name='name_en',
        ),
        migrations.RemoveField(
            model_name='paymenttype',
            name='usage_status',
        ),
    ]
