# Generated by Django 4.2.20 on 2025-04-14 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customs_general', '0003_rename_branches_number_bankbranches_branches_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankbranches',
            old_name='bank_connection',
            new_name='bank_id',
        ),
        migrations.RenameField(
            model_name='bankbranches',
            old_name='branches_name',
            new_name='name',
        ),
    ]
