# Generated by Django 4.2.20 on 2025-03-19 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customs_general', '0003_customertype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customertype',
            options={'verbose_name': 'Müşteri tipleri', 'verbose_name_plural': 'Müşteri tipleri'},
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='customs_code',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='customs_name',
        ),
    ]
