# Generated by Django 4.2.20 on 2025-04-16 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customs_general', '0004_rename_risk_status_paymenttype_name_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttype',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customs_general.datasource'),
        ),
    ]
