# Generated by Django 4.2.20 on 2025-03-13 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customs_general', '0004_alter_customsoffice_customs_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additionalinfocode',
            options={'verbose_name': 'Tamamlayıcı Bilgi Kodları', 'verbose_name_plural': 'Tamamlayıcı Bilgi Kodları'},
        ),
        migrations.AlterModelOptions(
            name='airlinecompany',
            options={'verbose_name': 'Uçak Şirketi Kodları', 'verbose_name_plural': 'Uçak Şirketi Kodları'},
        ),
        migrations.AlterModelOptions(
            name='airport',
            options={'verbose_name': 'Havalimanı Kodları', 'verbose_name_plural': 'Havalimanı Kodları'},
        ),
        migrations.AlterModelOptions(
            name='antidumpingcompany',
            options={'verbose_name': 'Anti-Damping Vergisi Üreticisi Gönderici Firma Kodları', 'verbose_name_plural': 'Anti-Damping Vergisi Üreticisi Gönderici Firma Kodları'},
        ),
        migrations.AlterModelOptions(
            name='bank',
            options={'verbose_name': 'Banka Kodları', 'verbose_name_plural': 'Banka Kodları'},
        ),
        migrations.AlterModelOptions(
            name='containercode',
            options={'verbose_name': 'Kap Kodları', 'verbose_name_plural': 'Kap Kodları'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Ülke Kodları', 'verbose_name_plural': 'Ülke Kodları'},
        ),
        migrations.AlterModelOptions(
            name='currencytype',
            options={'verbose_name': 'Döviz Cinsi Kodları', 'verbose_name_plural': 'Döviz Cinsi Kodları'},
        ),
        migrations.AlterModelOptions(
            name='customsoffice',
            options={'verbose_name': 'Gümrük İdareleri ve Saymanlık Kodları', 'verbose_name_plural': 'Gümrük İdareleri ve Saymanlık Kodları'},
        ),
        migrations.AlterModelOptions(
            name='deliverymethod',
            options={'verbose_name': 'Teslim Şekli Kodları', 'verbose_name_plural': 'Teslim Şekli Kodları'},
        ),
        migrations.AlterModelOptions(
            name='depot',
            options={'verbose_name': 'Antrepo Kodları', 'verbose_name_plural': 'Antrepo Kodları'},
        ),
        migrations.AlterModelOptions(
            name='exemptioncode',
            options={'verbose_name': 'Muafiyet Kodları', 'verbose_name_plural': 'Muafiyet Kodları'},
        ),
        migrations.AlterModelOptions(
            name='harbor',
            options={'verbose_name': 'Liman Kodları', 'verbose_name_plural': 'Liman Kodları'},
        ),
        migrations.AlterModelOptions(
            name='internationalagreement',
            options={'verbose_name': 'Uluslararası Anlaşma Kodları', 'verbose_name_plural': 'Uluslararası Anlaşma Kodları'},
        ),
        migrations.AlterModelOptions(
            name='measurementunit',
            options={'verbose_name': 'Ölçü Birimleri Kodları', 'verbose_name_plural': 'Ölçü Birimleri Kodları'},
        ),
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'verbose_name': 'Ödeme Şekilleri', 'verbose_name_plural': 'Ödeme Şekilleri'},
        ),
        migrations.AlterModelOptions(
            name='port',
            options={'verbose_name': 'Uluslararası Liman Kodları', 'verbose_name_plural': 'Uluslararası Liman Kodları'},
        ),
        migrations.AlterModelOptions(
            name='province',
            options={'verbose_name': 'STM bağlı il kodları', 'verbose_name_plural': 'STM bağlı il kodları'},
        ),
        migrations.AlterModelOptions(
            name='regimecode',
            options={'verbose_name': 'Rejim Kodları', 'verbose_name_plural': 'Rejim Kodları'},
        ),
        migrations.AlterModelOptions(
            name='requireddocument',
            options={'verbose_name': 'İstenen Döküman Kodları', 'verbose_name_plural': 'İstenen Döküman Kodları'},
        ),
        migrations.AlterModelOptions(
            name='simplifiedprocedure',
            options={'verbose_name': 'Basitleştirilmiş Usul Kodları', 'verbose_name_plural': 'Basitleştirilmiş Usul Kodları'},
        ),
        migrations.AlterModelOptions(
            name='taxcode',
            options={'verbose_name': 'Güncel Vergi Kodları', 'verbose_name_plural': 'Güncel Vergi Kodları'},
        ),
        migrations.AlterModelOptions(
            name='transactiontype',
            options={'verbose_name': 'İşlem Niteliği Kodları', 'verbose_name_plural': 'İşlem Niteliği Kodları'},
        ),
        migrations.AlterModelOptions(
            name='transporttype',
            options={'verbose_name': 'Taşıma Türleri Kodları', 'verbose_name_plural': 'Taşıma Türleri Kodları'},
        ),
        migrations.AlterModelOptions(
            name='transportvehicle',
            options={'verbose_name': 'Taşıma Araçları', 'verbose_name_plural': 'Taşıma Araçları'},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'verbose_name': 'Ambar Kodları', 'verbose_name_plural': 'Ambar Kodları'},
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='warehouse_code',
            field=models.CharField(max_length=10),
        ),
    ]
