# Generated by Django 4.2.20 on 2025-03-19 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customs_general', '0004_alter_customertype_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depot',
            name='customs_code',
        ),
        migrations.RemoveField(
            model_name='depot',
            name='customs_name',
        ),
        migrations.AddField(
            model_name='depot',
            name='customs_number',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customs_general.customsoffice'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='depot',
            name='warehouse_code',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customs_general.warehouse'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='depot',
            name='depot_code',
            field=models.CharField(max_length=60),
        ),
    ]
