# Generated by Django 4.2.20 on 2025-03-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customs_general', '0005_alter_additionalinfocode_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='port',
            name='country',
        ),
        migrations.AlterField(
            model_name='port',
            name='code',
            field=models.CharField(max_length=30),
        ),
    ]
