# Generated by Django 4.2.20 on 2025-03-19 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customs_general', '0005_remove_depot_customs_code_remove_depot_customs_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requireddocument',
            old_name='description',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='requireddocument',
            name='code',
            field=models.CharField(max_length=70),
        ),
    ]
