# Generated by Django 4.2.20 on 2025-03-19 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customs_general', '0006_rename_description_requireddocument_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Ödeme Tipleri',
                'verbose_name_plural': 'Ödeme Tipleri',
            },
        ),
        migrations.RenameField(
            model_name='containercode',
            old_name='description',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='taxcode',
            old_name='description',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='containercode',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='taxcode',
            name='code',
            field=models.CharField(max_length=100),
        ),
    ]
