# Generated by Django 4.2.20 on 2025-03-20 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customs_general', '0007_paymenttype_rename_description_containercode_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='country_number',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
