# Generated by Django 4.2.20 on 2025-03-20 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customs_general', '0008_country_country_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='country_code',
            new_name='country_code_en',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='country_name',
            new_name='country_code_tr',
        ),
        migrations.AddField(
            model_name='country',
            name='country_lang_code',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='country_name_en',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='country_name_tr',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='country_phone_code',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='currency_code',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
