# Generated by Django 4.2.20 on 2025-04-17 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customs_general', '0008_customsoffice_data_source'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'verbose_name': 'Ödeme Şekli', 'verbose_name_plural': 'Ödeme Şekilleri'},
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='group_leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_members', to='customs_general.paymentmethod', verbose_name='Grup Lideri'),
        ),
    ]
