# Generated by Django 4.2.20 on 2025-04-17 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customs_general', '0009_alter_paymentmethod_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='group_leader',
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='standard_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='localized_variants', to='customs_general.paymentmethod', verbose_name='Referans Standart Ödeme'),
        ),
    ]
