# Generated by Django 4.2.20 on 2025-03-20 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customs_general', '0009_rename_country_code_country_country_code_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantitytype',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
