# Generated by Django 4.2.20 on 2025-03-20 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customs_general', '0010_alter_quantitytype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantitytype',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
