# Generated by Django 4.2.20 on 2025-04-17 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customs_general', '0010_remove_paymentmethod_group_leader_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='origin_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customs_general.country', verbose_name='Kaynak Ülke'),
        ),
    ]
