# Generated by Django 4.2.20 on 2025-04-17 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customs_general', '0011_datasource_origin_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='is_global',
            field=models.BooleanField(default=False, verbose_name='Uluslararası Kayıt'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='standard_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='localized_variants', to='customs_general.paymentmethod', verbose_name='Muadil Referans'),
        ),
    ]
