# Generated by Django 4.2.20 on 2025-03-20 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customs_general', '0011_alter_quantitytype_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MeasurementUnit',
        ),
    ]
