# Generated by Django 4.2.20 on 2025-03-20 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customs_general', '0012_delete_measurementunit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='province',
            name='code',
            field=models.CharField(max_length=100),
        ),
    ]
