# Generated by Django 4.2.20 on 2025-04-17 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customs_general', '0012_datasource_is_global_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requireddocument',
            name='edi_code',
        ),
        migrations.AddField(
            model_name='requireddocument',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customs_general.datasource'),
        ),
    ]
