# Generated by Django 4.2.20 on 2025-04-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customs_general', '0013_remove_requireddocument_edi_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requireddocument',
            name='name_en',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
