# Generated by Django 4.2.20 on 2025-03-28 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customs_general', '0013_alter_province_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxcode',
            name='tax_ratio',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='GtipCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=255)),
                ('quantity', models.CharField(max_length=50)),
                ('tax_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customs_general.taxcode')),
            ],
        ),
    ]
