# Generated by Django 4.2.20 on 2025-04-18 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customs_general', '0015_deliverymethod_data_source'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Şehir', 'verbose_name_plural': 'Şehirler'},
        ),
        migrations.RemoveField(
            model_name='city',
            name='state',
        ),
        migrations.AddField(
            model_name='city',
            name='capitol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baskent_altindakiler', to='customs_general.city'),
        ),
        migrations.AddField(
            model_name='city',
            name='name_alternate',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='up_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alt_yerlesimler', to='customs_general.city'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
