# Generated by Django 4.2.20 on 2025-04-18 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customs_general', '0016_alter_city_options_remove_city_state_city_capitol_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='capitol',
            new_name='capitol_id',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='up_city',
            new_name='up_city_id',
        ),
    ]
