# Generated by Django 4.2.20 on 2025-04-20 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customs_general', '0017_rename_capitol_city_capitol_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
