# Generated by Django 4.2.20 on 2025-04-20 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customs_general', '0018_alter_datasource_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencytype',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
