# Generated by Django 4.2.20 on 2025-04-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customs_general', '0019_alter_currencytype_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencytype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
