# Generated by Django 4.2.20 on 2025-04-20 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customs_general', '0021_alter_currencytype_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='currency_id',
            new_name='currency',
        ),
    ]
