# Generated by Django 4.2.20 on 2025-04-20 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customs_general', '0022_rename_currency_id_country_currency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='capitol_id',
            new_name='capitol_city',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='up_city_id',
            new_name='up_city',
        ),
    ]
