# Generated by Django 4.2.20 on 2025-04-20 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customs_general', '0023_rename_capitol_id_city_capitol_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='country_id',
            new_name='country',
        ),
        migrations.AlterField(
            model_name='city',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
