# Generated by Django 4.2.20 on 2025-04-21 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customs_general', '0024_rename_country_id_city_country_alter_city_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name_alternate',
            field=models.TextField(blank=True, null=True),
        ),
    ]
