# Generated by Django 4.2.20 on 2025-04-21 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customs_general', '0025_alter_city_name_alternate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='port',
            old_name='city_id',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='port',
            old_name='country_id',
            new_name='country',
        ),
    ]
