# Generated by Django 4.2.20 on 2025-04-21 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customs_general', '0026_rename_city_id_port_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
