# Generated by Django 4.2.20 on 2025-04-21 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customs_general', '0029_alter_paymenttype_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customstype',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
