# Generated by Django 4.2.20 on 2025-04-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customs_general', '0030_alter_customstype_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customsoffice',
            old_name='chief_customs_id',
            new_name='chief_customs',
        ),
        migrations.RenameField(
            model_name='customsoffice',
            old_name='city_id',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='customsoffice',
            old_name='customs_type_id',
            new_name='customs_type',
        ),
        migrations.AlterField(
            model_name='customsoffice',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
