# Generated by Django 4.2.20 on 2025-04-21 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customs_general', '0031_rename_chief_customs_id_customsoffice_chief_customs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chiefcustomsoffice',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
