# Generated by Django 4.2.20 on 2025-04-21 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customs_general', '0034_airport_data_source_alter_airport_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airport',
            old_name='city_id',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='airport',
            old_name='country_id',
            new_name='country',
        ),
    ]
