# Generated by Django 4.2.20 on 2025-04-22 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customs_general', '0035_rename_city_id_airport_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverymethod',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
