# Generated by Django 4.2.20 on 2025-04-22 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customs_general', '0037_remove_taxcode_tax_ratio_taxcode_data_source_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transporttype',
            old_name='name_tr',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='transporttype',
            name='e_invoice_code',
        ),
        migrations.RemoveField(
            model_name='transporttype',
            name='edi_code',
        ),
        migrations.AddField(
            model_name='transporttype',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customs_general.datasource'),
        ),
        migrations.AlterField(
            model_name='transporttype',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
