# Generated by Django 4.2.20 on 2025-04-22 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customs_general', '0038_rename_name_tr_transporttype_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transporttype',
            name='transport_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasima_turleri', to='customs_general.transporttype'),
        ),
    ]
