# Generated by Django 4.2.20 on 2025-04-22 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customs_general', '0040_containercode_data_source_containercode_name_en_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankbranches',
            old_name='bank_id',
            new_name='bank',
        ),
        migrations.RenameField(
            model_name='bankbranches',
            old_name='city_id',
            new_name='city',
        ),
    ]
