# Generated by Django 4.2.20 on 2025-04-24 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customs_general', '0042_bankbranches_data_source_alter_bankbranches_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quantitytype',
            name='edi_code',
        ),
        migrations.AddField(
            model_name='quantitytype',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customs_general.datasource'),
        ),
        migrations.AddField(
            model_name='quantitytype',
            name='unit_symbol',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quantitytype',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
