# Generated by Django 4.2.20 on 2025-04-24 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customs_general', '0043_remove_quantitytype_edi_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantitytype',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='quantitytype',
            name='unit_symbol',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
