# Generated by Django 4.2.20 on 2025-04-24 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customs_general', '0044_alter_quantitytype_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customertype',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customs_general.datasource'),
        ),
        migrations.AlterField(
            model_name='customertype',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
