# Generated by Django 4.2.20 on 2025-04-25 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customs_general', '0046_transportvehicle_data_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportvehicle',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='transportvehicle',
            name='name_en',
            field=models.CharField(max_length=255),
        ),
    ]
