# Generated by Django 4.2.20 on 2025-04-25 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customs_general', '0047_alter_transportvehicle_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactiontype',
            old_name='description',
            new_name='name',
        ),
        migrations.AddField(
            model_name='transactiontype',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customs_general.datasource'),
        ),
        migrations.AlterField(
            model_name='transactiontype',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
