# Generated by Django 4.2.20 on 2025-04-29 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customs_general', '0048_rename_description_transactiontype_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Harbor',
        ),
    ]
