# Generated by Django 4.2.20 on 2025-04-29 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customs_general', '0052_internationalagreement_data_source_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simplifiedprocedure',
            old_name='description',
            new_name='name',
        ),
    ]
