# Generated by Django 4.2.20 on 2025-04-29 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customs_general', '0055_rename_description_exemptioncode_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regimecode',
            old_name='description',
            new_name='name',
        ),
        migrations.AddField(
            model_name='regimecode',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customs_general.datasource'),
        ),
        migrations.AlterField(
            model_name='regimecode',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
