# Generated by Django 4.2.20 on 2025-05-05 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customs_general', '0056_rename_description_regimecode_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gtipcode',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='gtipcode',
            name='tax_code',
        ),
        migrations.AddField(
            model_name='gtipcode',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customs_general.datasource'),
        ),
        migrations.AlterField(
            model_name='gtipcode',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
