# Generated by Django 4.2.20 on 2025-05-05 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customs_general', '0057_remove_gtipcode_quantity_remove_gtipcode_tax_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gtipcode',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
