# Generated by Django 4.2.20 on 2025-05-05 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customs_general', '0058_alter_gtipcode_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gtipcode',
            name='desc',
            field=models.TextField(null=True),
        ),
    ]
