# Generated by Django 4.2.20 on 2025-05-20 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customs_general', '0060_alter_additionalinfocode_id_alter_airport_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
