# Generated by Django 4.2.20 on 2025-03-24 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customs_general', '0013_alter_province_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100)),
                ('brand_code', models.CharField(max_length=100)),
                ('brand_activate_number', models.CharField(max_length=100)),
                ('brand_description', models.CharField(max_length=255)),
                ('brand_logo', models.ImageField(blank=True, null=True, upload_to='brand_logos/', verbose_name='Marka görseli')),
                ('activated_countries', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customs_general.country')),
            ],
        ),
    ]
