# Generated by Django 4.2.20 on 2025-04-15 11:37

import core.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customs_general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100)),
                ('brand_code', models.CharField(max_length=100)),
                ('brand_activate_number', models.CharField(max_length=100)),
                ('brand_description', models.CharField(max_length=255)),
                ('brand_logo', models.ImageField(blank=True, null=True, upload_to='brand_logos/', verbose_name='Marka görseli')),
                ('activated_countries', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customs_general.country')),
            ],
            options={
                'verbose_name': 'Marka',
                'verbose_name_plural': 'Marka',
            },
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_model', models.CharField(max_length=100)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.brand')),
            ],
            options={
                'verbose_name': 'Model',
                'verbose_name_plural': 'Model',
            },
        ),
        migrations.CreateModel(
            name='UploadedDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(max_length=255)),
                ('doc_file', models.FileField(upload_to=core.utils.date_based_upload_path)),
                ('doc_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customs_general.requireddocument')),
            ],
            options={
                'verbose_name': 'Yüklenen Dökümanlar',
                'verbose_name_plural': 'Yüklenen Dökümanlar',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=255)),
                ('prod_price', models.CharField(max_length=50)),
                ('prod_code', models.CharField(max_length=150)),
                ('prod_desc', models.CharField(max_length=255)),
                ('manufacturer', models.CharField(max_length=150)),
                ('manufacturer_stock_code', models.CharField(max_length=100)),
                ('package_lengths', models.CharField(max_length=100)),
                ('quantity_in_package', models.CharField(max_length=100)),
                ('kg', models.CharField(max_length=30)),
                ('kg_net', models.CharField(max_length=30)),
                ('package_barcode', models.CharField(max_length=30)),
                ('prod_img', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Ürün görseli')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.brand')),
                ('container_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customs_general.containercode')),
                ('currency_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customs_general.currencytype')),
                ('doc_name', models.ManyToManyField(blank=True, to='products.uploadeddocuments')),
                ('gtip_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customs_general.gtipcode')),
                ('manufacturer_country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customs_general.country')),
                ('prod_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productmodel')),
                ('quantity_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customs_general.quantitytype')),
                ('tax_code', models.ManyToManyField(blank=True, to='customs_general.taxcode')),
            ],
            options={
                'verbose_name': 'Ürünler',
                'verbose_name_plural': 'Ürünler',
            },
        ),
    ]
