# Generated by Django 4.2.20 on 2025-06-03 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customs_general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('record_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('system_note', models.TextField(blank=True, null=True)),
                ('brand_name', models.CharField(max_length=100)),
                ('brand_code', models.CharField(max_length=100)),
                ('brand_activate_number', models.CharField(max_length=100)),
                ('brand_description', models.CharField(max_length=255)),
                ('brand_logo', models.ImageField(blank=True, null=True, upload_to='brand_logos/', verbose_name='Marka görseli')),
                ('activated_countries', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customs_general.country')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Marka',
                'verbose_name_plural': 'Marka',
            },
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('record_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('system_note', models.TextField(blank=True, null=True)),
                ('product_model', models.CharField(max_length=100)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.brand')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Model',
                'verbose_name_plural': 'Model',
            },
        ),
        migrations.CreateModel(
            name='UploadedDocuments',
            fields=[
                ('uploadeddocumentsbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.uploadeddocumentsbase')),
                ('doc_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customs_general.requireddocument')),
            ],
            options={
                'verbose_name': 'Yüklenen Dökümanlar',
                'verbose_name_plural': 'Yüklenen Dökümanlar',
            },
            bases=('core.uploadeddocumentsbase',),
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('record_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('system_note', models.TextField(blank=True, null=True)),
                ('prod_name', models.CharField(max_length=255)),
                ('prod_price', models.CharField(max_length=50)),
                ('prod_code', models.CharField(max_length=150)),
                ('prod_desc', models.CharField(max_length=255)),
                ('manufacturer', models.CharField(max_length=150)),
                ('manufacturer_stock_code', models.CharField(max_length=100)),
                ('package_lengths', models.CharField(max_length=100)),
                ('quantity_in_package', models.CharField(max_length=100)),
                ('kg', models.CharField(max_length=30)),
                ('kg_net', models.CharField(max_length=30)),
                ('package_barcode', models.CharField(max_length=30)),
                ('prod_img', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Ürün görseli')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.brand')),
                ('container_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customs_general.containercode')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('currency_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customs_general.currencytype')),
                ('doc_name', models.ManyToManyField(blank=True, to='products.uploadeddocuments')),
                ('gtip_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customs_general.gtipcode')),
                ('manufacturer_country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customs_general.country')),
                ('prod_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productmodel')),
                ('quantity_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customs_general.quantitytype')),
                ('tax_code', models.ManyToManyField(blank=True, to='customs_general.taxcode')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ürünler',
                'verbose_name_plural': 'Ürünler',
            },
        ),
    ]
