# Generated by Django 4.2.20 on 2025-03-28 07:30

import core.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customs_general', '0013_alter_province_code'),
        ('products', '0002_productmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Marka', 'verbose_name_plural': 'Marka'},
        ),
        migrations.AlterModelOptions(
            name='productmodel',
            options={'verbose_name': 'Model', 'verbose_name_plural': 'Model'},
        ),
        migrations.CreateModel(
            name='UploadedDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(max_length=255)),
                ('doc_file', models.FileField(upload_to=core.utils.date_based_upload_path)),
                ('doc_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customs_general.requireddocument')),
            ],
        ),
    ]
