# Generated by Django 4.2.20 on 2025-03-28 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customs_general', '0014_taxcode_tax_ratio_gtipcode'),
        ('products', '0003_alter_brand_options_alter_productmodel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=255)),
                ('prod_price', models.CharField(max_length=50)),
                ('prod_code', models.CharField(max_length=150)),
                ('prod_desc', models.CharField(max_length=255)),
                ('manufacturer', models.CharField(max_length=150)),
                ('manufacturer_stock_code', models.CharField(max_length=100)),
                ('package_lengths', models.CharField(max_length=100)),
                ('quantity_in_package', models.CharField(max_length=100)),
                ('kg', models.CharField(max_length=30)),
                ('kg_net', models.CharField(max_length=30)),
                ('package_barcode', models.CharField(max_length=30)),
                ('prod_img', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Ürün görseli')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.brand')),
                ('container_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customs_general.containercode')),
                ('currency_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customs_general.currencytype')),
                ('doc_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.uploadeddocuments')),
                ('gtip_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customs_general.gtipcode')),
                ('manufacturer_country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customs_general.country')),
                ('prod_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productmodel')),
                ('quantity_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customs_general.quantitytype')),
                ('tax_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customs_general.taxcode')),
            ],
        ),
    ]
