# Generated by Django 4.2.20 on 2025-04-02 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customs_general', '0014_taxcode_tax_ratio_gtipcode'),
        ('products', '0004_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'ürünler', 'verbose_name_plural': 'ürünler'},
        ),
        migrations.AlterModelOptions(
            name='uploadeddocuments',
            options={'verbose_name': 'Yüklenen Dökümanlar', 'verbose_name_plural': 'Yüklenen Dökümanlar'},
        ),
        migrations.RemoveField(
            model_name='products',
            name='tax_code',
        ),
        migrations.AddField(
            model_name='products',
            name='tax_code',
            field=models.ManyToManyField(blank=True, to='customs_general.taxcode'),
        ),
    ]
